/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.3.3/userguide/multi_project_builds.html
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "festival-garden"
include("festival-wizard-scraper")
include("festival-garden-api")
include("festival-garden-interchange")
include("spotify-client")
include("festival-garden-db-models")
include("festival-garden-web-client")
include("queue-service-abstraction")
include("festival-garden-message-handler")
include("local-deployment")
include("aws-deployment")
include("aws-client-deployment")
include("shared-backend-utils")
include("db-auto-maintanince")
